'use client';

import { useEffect } from 'react';

/**
 * Registers the service worker (public/sw.js, generated by Serwist
 * at build time from src/app/sw.ts).
 *
 * PSP-023: enables true offline PWA support. The app shell, static
 * assets, and API responses (via runtime caching) are cached so the
 * app loads without a network after first visit.
 *
 * Disabled in development (Serwist's `disable: process.env.NODE_ENV
 * === 'development'` in next.config.ts skips SW generation in dev).
 */
export function ServiceWorkerRegister() {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!('serviceWorker' in navigator)) return;
    // Only register in production — dev is handled by next-pwa/serwist
    // with a different flow, and we set `disable: dev` in next.config.
    if (process.env.NODE_ENV !== 'production') return;

    const register = () => {
      navigator.serviceWorker
        .register('/sw.js', { scope: '/' })
        .then((reg) => {
          // Check for updates every hour.
          reg.update();
        })
        .catch((err) => {
          console.warn('Service worker registration failed:', err);
        });
    };

    // Register after window load to avoid competing with first paint.
    if (document.readyState === 'complete') {
      register();
    } else {
      window.addEventListener('load', register);
      return () => window.removeEventListener('load', register);
    }
  }, []);

  return null;
}
